# Generated by Django 5.2.8 on 2025-12-18 07:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('web', 'Web Development'), ('software', 'Software Development'), ('digital', 'Digital Marketing')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
