# Generated by Django 5.2.8 on 2025-12-18 07:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDevelopmentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('hero_image', models.ImageField(upload_to='web/')),
            ],
        ),
        migrations.CreateModel(
            name='WebFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Example: bx bx-code-alt', max_length=50)),
                ('bg_color', models.CharField(help_text='Tailwind color: bg-red-100, bg-green-100', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.webdevelopmentpage')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
