# Generated by Django 5.2.8 on 2025-12-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_webdevelopmentpage_webfeature_delete_servicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='web/services/')),
                ('image_position', models.CharField(choices=[('left', 'Image Left'), ('right', 'Image Right')], default='right', max_length=10)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sections', to='pages.webdevelopmentpage')),
            ],
        ),
    ]
