# Generated by Django 5.2.8 on 2025-12-18 09:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pricingplan_pricingfeature_pricingsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', ckeditor.fields.RichTextField()),
                ('hero_image', models.ImageField(upload_to='home/hero/')),
                ('cta_text', models.CharField(default='Get Started', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='button_text',
            field=models.CharField(default='Buy Now', max_length=50),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/projects/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='home/testimonials/')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='WhyBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=50)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_best', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='home/process/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='pages.homepage')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
