# Generated by Django 5.2.8 on 2025-12-18 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepage_alter_pricingplan_button_text_faq_homestat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
