# Generated by Django 5.2.8 on 2025-12-18 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_homepage_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='whybest',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/whybest/'),
            preserve_default=False,
        ),
    ]
