# Generated by Django 5.2.8 on 2025-12-18 10:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_whybest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyBestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='home/why-best/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyBestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('icon_class', models.CharField(help_text='Example: bx bx-time-five', max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='pages.whybestsection')),
            ],
        ),
        migrations.DeleteModel(
            name='WhyBest',
        ),
    ]
