# Generated by Django 5.2.8 on 2025-12-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_whybestsection_whybestpoint_delete_whybest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whybestpoint',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='whybestpoint',
            name='image',
            field=models.ImageField(default=1, upload_to='home/why-best-point/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whybestsection',
            name='highlight_word',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whybestsection',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_best_sections', to='pages.homepage'),
        ),
    ]
