# Generated by Django 5.2.8 on 2025-12-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_whybestpoint_icon_class_whybestpoint_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workprocess',
            options={},
        ),
        migrations.RenameField(
            model_name='workprocess',
            old_name='icon',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='workprocess',
            name='step_number',
        ),
        migrations.RemoveField(
            model_name='workprocess',
            name='title',
        ),
    ]
