# Generated by Django 5.2.8 on 2025-12-18 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_workprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprocess',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
