# Generated by Django 5.2.8 on 2025-12-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_workprocess_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprocess',
            name='title',
        ),
    ]
