# Generated by Django 5.2.8 on 2025-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_workprocess_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('web', 'web_devlopment'), ('software', 'software_devlopment'), ('digital', 'digital_marketing')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('image_position', models.CharField(choices=[('left', 'Image Left'), ('right', 'Image Right')], default='right', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='WebServiceSection',
        ),
    ]
