# Generated by Django 5.2.8 on 2025-12-18 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_servicesection_delete_webservicesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingsection',
            name='page',
        ),
        migrations.AddField(
            model_name='pricingsection',
            name='page_type',
            field=models.CharField(choices=[('web', 'web_devlopment'), ('digital', 'digital_marketing')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
