# Generated by Django 5.2.8 on 2025-12-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_pricingsection_page_pricingsection_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesection',
            name='page_type',
            field=models.CharField(choices=[('web', 'web_devlopment'), ('software', 'software_devlopment'), ('digital', 'digital_marketing'), ('about', 'about_us')], max_length=20),
        ),
    ]
